/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab_8_brauliocalix;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        adminClientes ap = new adminClientes("./CLIENTES.HOLADIEGO");
        ap.cargarArchivo();
        cli = ap.getListaPersonas();
        tamano_lista.setText("en la lista hay: " + cli.size() + " clientes");
        comida.add(new comida("hamburgesa", 20, 75, 100));
        comida.add(new comida("sandiwiches", 15, 90, 100));
        comida.add(new comida("boneless", 12, 90, 100));
        comida.add(new comida("almuerzo normal", 25, 100, 100));
        comida.add(new comida("nacho", 20, 100, 100));
        comida.add(new comida("alitas", 20, 120, 100));
        comida.add(new comida("baleada normal", 15, 15, 100));
        comida.add(new comida("baleada con todo", 20, 35, 100));
        comida.add(new comida("gringas", 17, 55, 100));
        comida.add(new comida("bebida", 0, 90, 100));
        comida.add(new comida("la excepcion en rocas", 0, 150, 100));
        adminAlimentos ad= new adminAlimentos("./INVENTARIO.HOLADIEGO");
        ad.setListaPersonas(comida);
        ad.escribirArchivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crear = new javax.swing.JDialog();
        normal = new javax.swing.JButton();
        UNITEC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        unitec = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        uni_nombre = new javax.swing.JTextField();
        uni_apellido = new javax.swing.JTextField();
        uni_billete = new javax.swing.JTextField();
        uni_cuenta = new javax.swing.JTextField();
        uni_tarjeta = new javax.swing.JComboBox<>();
        creaUni = new javax.swing.JButton();
        cliente = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cli_nombre = new javax.swing.JTextField();
        cli_apellido = new javax.swing.JTextField();
        cli_billete = new javax.swing.JTextField();
        cli_tarjeta = new javax.swing.JComboBox<>();
        creanormal = new javax.swing.JButton();
        inventario = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        simulacion = new javax.swing.JDialog();
        mostrar_inventar = new javax.swing.JButton();
        modificar = new javax.swing.JDialog();
        modi_combo = new javax.swing.JComboBox<>();
        modi_efec = new javax.swing.JTextField();
        modi_cargo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bt_modifica = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        iniciar = new javax.swing.JButton();
        crea_cliente = new javax.swing.JButton();
        tamano_lista = new javax.swing.JLabel();
        modifi = new javax.swing.JButton();

        normal.setText("cliente normal");
        normal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                normalMouseClicked(evt);
            }
        });

        UNITEC.setText("unitec");
        UNITEC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UNITECMouseClicked(evt);
            }
        });

        jLabel1.setText("QUE TIPO DE CLIENTE VA A CREAR");

        javax.swing.GroupLayout crearLayout = new javax.swing.GroupLayout(crear.getContentPane());
        crear.getContentPane().setLayout(crearLayout);
        crearLayout.setHorizontalGroup(
            crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(normal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(UNITEC)
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(96, 96, 96))
        );
        crearLayout.setVerticalGroup(
            crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(normal)
                    .addComponent(UNITEC))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel2.setText("nombre");

        jLabel3.setText("apellido");

        jLabel4.setText("tarjeta");

        jLabel5.setText("billetera");

        jLabel6.setText("numero de cuenta");

        uni_tarjeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "amex", "visa" }));

        creaUni.setText("crear");
        creaUni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creaUniMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout unitecLayout = new javax.swing.GroupLayout(unitec.getContentPane());
        unitec.getContentPane().setLayout(unitecLayout);
        unitecLayout.setHorizontalGroup(
            unitecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unitecLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(unitecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addGroup(unitecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(uni_apellido)
                    .addComponent(uni_nombre)
                    .addComponent(uni_billete)
                    .addComponent(uni_cuenta)
                    .addComponent(uni_tarjeta, 0, 83, Short.MAX_VALUE))
                .addGap(176, 176, 176))
            .addGroup(unitecLayout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(creaUni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        unitecLayout.setVerticalGroup(
            unitecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unitecLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(unitecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(uni_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(unitecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(uni_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(unitecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(uni_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(unitecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(uni_billete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(unitecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(uni_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(creaUni)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel7.setText("nombre");

        jLabel8.setText("apellido");

        jLabel9.setText("tarjeta");

        jLabel10.setText("billetera");

        cli_tarjeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "amex", "visa" }));

        creanormal.setText("crear");
        creanormal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creanormalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout clienteLayout = new javax.swing.GroupLayout(cliente.getContentPane());
        cliente.getContentPane().setLayout(clienteLayout);
        clienteLayout.setHorizontalGroup(
            clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clienteLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cli_apellido)
                    .addComponent(cli_nombre)
                    .addComponent(cli_billete)
                    .addComponent(cli_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
            .addGroup(clienteLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(creanormal)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        clienteLayout.setVerticalGroup(
            clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clienteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cli_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cli_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cli_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cli_billete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(creanormal)
                .addGap(25, 25, 25))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Alimentos", "tiempo-mins", "precio", "cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout inventarioLayout = new javax.swing.GroupLayout(inventario.getContentPane());
        inventario.getContentPane().setLayout(inventarioLayout);
        inventarioLayout.setHorizontalGroup(
            inventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventarioLayout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        inventarioLayout.setVerticalGroup(
            inventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventarioLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        mostrar_inventar.setText("mostrar inventario");
        mostrar_inventar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrar_inventarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout simulacionLayout = new javax.swing.GroupLayout(simulacion.getContentPane());
        simulacion.getContentPane().setLayout(simulacionLayout);
        simulacionLayout.setHorizontalGroup(
            simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, simulacionLayout.createSequentialGroup()
                .addContainerGap(925, Short.MAX_VALUE)
                .addComponent(mostrar_inventar)
                .addGap(38, 38, 38))
        );
        simulacionLayout.setVerticalGroup(
            simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simulacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mostrar_inventar)
                .addContainerGap(548, Short.MAX_VALUE))
        );

        modi_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                modi_comboItemStateChanged(evt);
            }
        });

        jLabel11.setText("efectivo");

        jLabel12.setText("cargo en la tarjeta");

        jLabel15.setText("seleccione el cliente a modificar");

        bt_modifica.setText("modificar");
        bt_modifica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modificaMouseClicked(evt);
            }
        });

        eliminar.setText("eliminar");
        eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout modificarLayout = new javax.swing.GroupLayout(modificar.getContentPane());
        modificar.getContentPane().setLayout(modificarLayout);
        modificarLayout.setHorizontalGroup(
            modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modi_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modi_efec)
                    .addComponent(modi_cargo))
                .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificarLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(31, 31, 31))))
            .addGroup(modificarLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(bt_modifica)
                .addGap(88, 88, 88)
                .addComponent(eliminar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        modificarLayout.setVerticalGroup(
            modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modi_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(57, 57, 57)
                .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(modificarLayout.createSequentialGroup()
                        .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modi_efec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(51, 51, 51)
                        .addComponent(modi_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_modifica)
                    .addComponent(eliminar))
                .addGap(34, 34, 34))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iniciar.setText("iniciar ");
        iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarMouseClicked(evt);
            }
        });

        crea_cliente.setText("crear cliente");
        crea_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crea_clienteMouseClicked(evt);
            }
        });

        tamano_lista.setText("jLabel1");

        modifi.setText("eliminar o modificar");
        modifi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tamano_lista, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(crea_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(iniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(modifi)))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(tamano_lista)
                .addGap(36, 36, 36)
                .addComponent(crea_cliente)
                .addGap(29, 29, 29)
                .addComponent(modifi)
                .addGap(35, 35, 35)
                .addComponent(iniciar)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UNITECMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UNITECMouseClicked
        // TODO add your handling code here:
        unitec.setModal(true);
        unitec.pack();
        unitec.setVisible(true);
    }//GEN-LAST:event_UNITECMouseClicked

    private void crea_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crea_clienteMouseClicked
        // TODO add your handling code here:
        crear.setVisible(true);
        crear.pack();
        crear.setVisible(true);
    }//GEN-LAST:event_crea_clienteMouseClicked

    private void normalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_normalMouseClicked
        // TODO add your handling code here:
        cliente.setModal(true);
        cliente.pack();
        cliente.setVisible(true);
    }//GEN-LAST:event_normalMouseClicked

    private void creaUniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creaUniMouseClicked
        // TODO add your handling code here:

        adminClientes ap = new adminClientes("./CLIENTES.HOLADIEGO");
        ap.cargarArchivo();

        String nombre = uni_nombre.getText();
        String apellido = uni_apellido.getText();
        String tarjeta = (String) uni_tarjeta.getSelectedItem();
        String cuenta = uni_cuenta.getText();
        int billete = 0;

        try {
            billete = Integer.parseInt(uni_billete.getText());

            //cli.add(new clienteuni(cuenta, nombre, apellido, tarjeta, 0, billete));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(unitec, "no se pudo crear el cliente");
        }
        cliente p = new clienteuni(cuenta, nombre, apellido, tarjeta, 0, billete);
        ap.setpersona(p);
        ap.escribirArchivo();
        // int billete=Integer.parseInt(uni_billete.getText()) ;
        //String cuenta, String nombre, String apellido, String tarjeta, int pagado, int billete
        JOptionPane.showMessageDialog(unitec, "se creo el cliente");
        cli= ap.getListaPersonas();
        tamano_lista.setText("en la lista hay: " + cli.size() + " clientes");
        unitec.dispose();
        crear.dispose();


    }//GEN-LAST:event_creaUniMouseClicked

    private void creanormalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creanormalMouseClicked
        // TODO add your handling code here:
        adminClientes ap = new adminClientes("./CLIENTES.HOLADIEGO");
        ap.cargarArchivo();
        String nombre = cli_nombre.getText();
        String apellido = cli_apellido.getText();
        String tarjeta = (String) cli_tarjeta.getSelectedItem();
        int billete = 0;
        try {
            billete = Integer.parseInt(cli_billete.getText());
            //cli.add(new cliente(nombre, apellido, tarjeta, 0, billete));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(cliente, "no se pudo crear el cliente");
        }
        cliente p = new cliente(nombre, apellido, tarjeta, 0, billete);
        ap.setpersona(p);
        ap.escribirArchivo();

        JOptionPane.showMessageDialog(unitec, "se creo el cliente");
        cli = ap.getListaPersonas();
        tamano_lista.setText("en la lista hay: " + cli.size() + " clientes");
        
        for (int i = 0; i < cli.size(); i++) {
            System.out.println(cli.get(i).toString() + "\n");
        }

        cliente.dispose();
        crear.dispose();

    }//GEN-LAST:event_creanormalMouseClicked

    private void mostrar_inventarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrar_inventarMouseClicked
        // TODO add your handling code here:

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Alimentos", "tiempo-mins", "precio", "cantidad"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        for (comida t : comida) {
            Object row[] = {t.getNombre(), t.getTiempo(), t.getPrecio(), t.getCantidad()};
            DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
            m.addRow(row);
            jTable1.setModel(m);
        }
        inventario.setModal(true);
        inventario.pack();
        inventario.setVisible(true);
    }//GEN-LAST:event_mostrar_inventarMouseClicked

    private void iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarMouseClicked
        // TODO add your handling code here:
        simulacion.setModal(true);
        simulacion.pack();
        simulacion.setVisible(true);
    }//GEN-LAST:event_iniciarMouseClicked

    private void modifiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifiMouseClicked
        // TODO add your handling code here:
        adminClientes ap = new adminClientes("./CLIENTES.HOLADIEGO");
        ap.cargarArchivo();
        
        cli = ap.getListaPersonas();
       /* 
        modi_combo.removeAll();
        //modi_combo.removeAllItems();
        
        for (int i = 0; i < cli.size(); i++) {
            modi_combo.addItem(cli.get(i).getNombre());
        }
        */
        DefaultComboBoxModel modelo= new DefaultComboBoxModel(cli.toArray());
        modi_combo.setModel(modelo);
        modificar.setModal(true);
        modificar.pack();
        modificar.setVisible(true);
    }//GEN-LAST:event_modifiMouseClicked

    private void modi_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_modi_comboItemStateChanged
        // TODO add your handling code here:
        adminClientes ap = new adminClientes("./CLIENTES.HOLADIEGO");
        ap.cargarArchivo();
        cli = ap.getListaPersonas();
        int pos=modi_combo.getSelectedIndex();
        modi_cargo.setText(Integer.toString(cli.get(pos).getPagado()));
        modi_efec.setText(Integer.toString(cli.get(pos).getBillete()));  
    }//GEN-LAST:event_modi_comboItemStateChanged

    private void eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarMouseClicked
        // TODO add your handling code here:
        int pos =modi_combo.getSelectedIndex();
        adminClientes ap = new adminClientes("./CLIENTES.HOLADIEGO");
        ap.cargarArchivo();
        ap.getListaPersonas().remove(pos);
        ap.escribirArchivo();
        JOptionPane.showMessageDialog(this, "se elimino de forma correcta");
        cli= ap.getListaPersonas();
        tamano_lista.setText("en la lista hay: " + cli.size() + " clientes");
        modificar.dispose();
    }//GEN-LAST:event_eliminarMouseClicked

    private void bt_modificaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modificaMouseClicked
        // TODO add your handling code here:
       adminClientes ap = new adminClientes("./CLIENTES.HOLADIEGO");
        ap.cargarArchivo();
        int pos=modi_combo.getSelectedIndex();
        ap.getListaPersonas().get(pos).setBillete(Integer.parseInt(modi_efec.getText()));
        ap.getListaPersonas().get(pos).setPagado(Integer.parseInt(modi_cargo.getText()));
        ap.escribirArchivo();
        JOptionPane.showMessageDialog(this, "se modifico de forma correcta");
        cli= ap.getListaPersonas();
        tamano_lista.setText("en la lista hay: " + cli.size() + " clientes");
        modificar.dispose();
    }//GEN-LAST:event_bt_modificaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UNITEC;
    private javax.swing.JButton bt_modifica;
    private javax.swing.JTextField cli_apellido;
    private javax.swing.JTextField cli_billete;
    private javax.swing.JTextField cli_nombre;
    private javax.swing.JComboBox<String> cli_tarjeta;
    private javax.swing.JDialog cliente;
    private javax.swing.JButton creaUni;
    private javax.swing.JButton crea_cliente;
    private javax.swing.JButton creanormal;
    private javax.swing.JDialog crear;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton iniciar;
    private javax.swing.JDialog inventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField modi_cargo;
    private javax.swing.JComboBox<String> modi_combo;
    private javax.swing.JTextField modi_efec;
    private javax.swing.JButton modifi;
    private javax.swing.JDialog modificar;
    private javax.swing.JButton mostrar_inventar;
    private javax.swing.JButton normal;
    private javax.swing.JDialog simulacion;
    private javax.swing.JLabel tamano_lista;
    private javax.swing.JTextField uni_apellido;
    private javax.swing.JTextField uni_billete;
    private javax.swing.JTextField uni_cuenta;
    private javax.swing.JTextField uni_nombre;
    private javax.swing.JComboBox<String> uni_tarjeta;
    private javax.swing.JDialog unitec;
    // End of variables declaration//GEN-END:variables
    //cconthambliente cli= new cliente();

    ArrayList<cliente> cli = new ArrayList();
    ArrayList<comida> comida = new ArrayList();
    
}
